server:
  port: 9999

spring:
  jmx:
    enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/ddd?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    open-in-view: false